### ISSUE TITLE
problemas en api/v1/dojo/users/{uid}/cv

### ISSUE THREAD

**Issue by NearTox** [devf-dojo/dojo-api#16]
hacer get en:
http://localhost:5000/devf-dojo-admin/us-central1/api/v1/dojo/users/1/cv
actualmente regresa: `200` : `null`

hacer post en
http://localhost:5000/devf-dojo-admin/us-central1/api/v1/dojo/users/1/cv
regresa: `201` : `{"status": "created"}`

**Comment by cassina** [comment]
@ManoloBrn @NearTox Podemos confirmar si ya podemos cerrar este issue o todavía es necesario?
