### ISSUE TITLE
Previo al MVP

### ISSUE THREAD

**Issue by cassina** [devf-dojo/dojo-api#7]
- Documentar nuestro el proyecto hasta el momento.
- Establecer reglas de nuestros tests.
- Establecer seguridad.
- Hacer un deploy a producción.

**Comment by ManoloBrn** [comment]
Solo falta reglas de test, lo demás ya se encuentra listo

**Comment by cassina** [comment]
Quedan pendientes las reglas para tests, se cubren en issue #24
